/*
 * _standard.h
 * generated by noweb
 */
#ifndef INCLUDE__COMPAT__STANDARD_H_
#define INCLUDE__COMPAT__STANDARD_H_

#include <stdlib.h>
#include <stdarg.h>

#ifndef no_c11
  #include <stdbool.h>
#else
typedef enum {
  false = 0,
  true = 1
} bool;
#ifndef no_inline
  #define no_inline
#endif
#endif


#if defined(with_watcominline)
        #define INLINE __inline
#elif !defined(no_inline)
        #define INLINE inline
#else
        #define INLINE
#endif

#endif /* INCLUDE__COMPAT__STANDARD_H_ */
